/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage.impl;

import hu.bme.mit.modes3.test.testLanguage.DivergentExpectation;
import hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Divergent Expectation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl#getDivergentExpectedState <em>Divergent Expected State</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl#getDivID <em>Div ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DivergentExpectationImpl extends MinimalEObjectImpl.Container implements DivergentExpectation
{
  /**
   * The default value of the '{@link #getDivergentExpectedState() <em>Divergent Expected State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivergentExpectedState()
   * @generated
   * @ordered
   */
  protected static final String DIVERGENT_EXPECTED_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDivergentExpectedState() <em>Divergent Expected State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivergentExpectedState()
   * @generated
   * @ordered
   */
  protected String divergentExpectedState = DIVERGENT_EXPECTED_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getDivID() <em>Div ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivID()
   * @generated
   * @ordered
   */
  protected static final int DIV_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDivID() <em>Div ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivID()
   * @generated
   * @ordered
   */
  protected int divID = DIV_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DivergentExpectationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestLanguagePackage.Literals.DIVERGENT_EXPECTATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDivergentExpectedState()
  {
    return divergentExpectedState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDivergentExpectedState(String newDivergentExpectedState)
  {
    String oldDivergentExpectedState = divergentExpectedState;
    divergentExpectedState = newDivergentExpectedState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE, oldDivergentExpectedState, divergentExpectedState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getDivID()
  {
    return divID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDivID(int newDivID)
  {
    int oldDivID = divID;
    divID = newDivID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.DIVERGENT_EXPECTATION__DIV_ID, oldDivID, divID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE:
        return getDivergentExpectedState();
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIV_ID:
        return getDivID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE:
        setDivergentExpectedState((String)newValue);
        return;
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIV_ID:
        setDivID((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE:
        setDivergentExpectedState(DIVERGENT_EXPECTED_STATE_EDEFAULT);
        return;
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIV_ID:
        setDivID(DIV_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE:
        return DIVERGENT_EXPECTED_STATE_EDEFAULT == null ? divergentExpectedState != null : !DIVERGENT_EXPECTED_STATE_EDEFAULT.equals(divergentExpectedState);
      case TestLanguagePackage.DIVERGENT_EXPECTATION__DIV_ID:
        return divID != DIV_ID_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (divergentExpectedState: ");
    result.append(divergentExpectedState);
    result.append(", divID: ");
    result.append(divID);
    result.append(')');
    return result.toString();
  }

} //DivergentExpectationImpl
