/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage.impl;

import hu.bme.mit.modes3.test.testLanguage.DivergentSection;
import hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Divergent Section</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentSectionImpl#getDivergentSectionState <em>Divergent Section State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DivergentSectionImpl extends MinimalEObjectImpl.Container implements DivergentSection
{
  /**
   * The default value of the '{@link #getDivergentSectionState() <em>Divergent Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivergentSectionState()
   * @generated
   * @ordered
   */
  protected static final String DIVERGENT_SECTION_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDivergentSectionState() <em>Divergent Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDivergentSectionState()
   * @generated
   * @ordered
   */
  protected String divergentSectionState = DIVERGENT_SECTION_STATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DivergentSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestLanguagePackage.Literals.DIVERGENT_SECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDivergentSectionState()
  {
    return divergentSectionState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDivergentSectionState(String newDivergentSectionState)
  {
    String oldDivergentSectionState = divergentSectionState;
    divergentSectionState = newDivergentSectionState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.DIVERGENT_SECTION__DIVERGENT_SECTION_STATE, oldDivergentSectionState, divergentSectionState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_SECTION__DIVERGENT_SECTION_STATE:
        return getDivergentSectionState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_SECTION__DIVERGENT_SECTION_STATE:
        setDivergentSectionState((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_SECTION__DIVERGENT_SECTION_STATE:
        setDivergentSectionState(DIVERGENT_SECTION_STATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.DIVERGENT_SECTION__DIVERGENT_SECTION_STATE:
        return DIVERGENT_SECTION_STATE_EDEFAULT == null ? divergentSectionState != null : !DIVERGENT_SECTION_STATE_EDEFAULT.equals(divergentSectionState);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (divergentSectionState: ");
    result.append(divergentSectionState);
    result.append(')');
    return result.toString();
  }

} //DivergentSectionImpl
