/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage.impl;

import hu.bme.mit.modes3.test.testLanguage.StraightExpectation;
import hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Straight Expectation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.StraightExpectationImpl#getStraightExpectedState <em>Straight Expected State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StraightExpectationImpl extends MinimalEObjectImpl.Container implements StraightExpectation
{
  /**
   * The default value of the '{@link #getStraightExpectedState() <em>Straight Expected State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStraightExpectedState()
   * @generated
   * @ordered
   */
  protected static final String STRAIGHT_EXPECTED_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStraightExpectedState() <em>Straight Expected State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStraightExpectedState()
   * @generated
   * @ordered
   */
  protected String straightExpectedState = STRAIGHT_EXPECTED_STATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StraightExpectationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestLanguagePackage.Literals.STRAIGHT_EXPECTATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStraightExpectedState()
  {
    return straightExpectedState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStraightExpectedState(String newStraightExpectedState)
  {
    String oldStraightExpectedState = straightExpectedState;
    straightExpectedState = newStraightExpectedState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE, oldStraightExpectedState, straightExpectedState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TestLanguagePackage.STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE:
        return getStraightExpectedState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TestLanguagePackage.STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE:
        setStraightExpectedState((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE:
        setStraightExpectedState(STRAIGHT_EXPECTED_STATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE:
        return STRAIGHT_EXPECTED_STATE_EDEFAULT == null ? straightExpectedState != null : !STRAIGHT_EXPECTED_STATE_EDEFAULT.equals(straightExpectedState);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (straightExpectedState: ");
    result.append(straightExpectedState);
    result.append(')');
    return result.toString();
  }

} //StraightExpectationImpl
