/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage.impl;

import hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage;
import hu.bme.mit.modes3.test.testLanguage.TopSection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Top Section</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl#getTopSectionState <em>Top Section State</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl#getTopID <em>Top ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TopSectionImpl extends MinimalEObjectImpl.Container implements TopSection
{
  /**
   * The default value of the '{@link #getTopSectionState() <em>Top Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopSectionState()
   * @generated
   * @ordered
   */
  protected static final String TOP_SECTION_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTopSectionState() <em>Top Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopSectionState()
   * @generated
   * @ordered
   */
  protected String topSectionState = TOP_SECTION_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getTopID() <em>Top ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopID()
   * @generated
   * @ordered
   */
  protected static final int TOP_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTopID() <em>Top ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopID()
   * @generated
   * @ordered
   */
  protected int topID = TOP_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TopSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestLanguagePackage.Literals.TOP_SECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTopSectionState()
  {
    return topSectionState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTopSectionState(String newTopSectionState)
  {
    String oldTopSectionState = topSectionState;
    topSectionState = newTopSectionState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.TOP_SECTION__TOP_SECTION_STATE, oldTopSectionState, topSectionState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTopID()
  {
    return topID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTopID(int newTopID)
  {
    int oldTopID = topID;
    topID = newTopID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestLanguagePackage.TOP_SECTION__TOP_ID, oldTopID, topID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TestLanguagePackage.TOP_SECTION__TOP_SECTION_STATE:
        return getTopSectionState();
      case TestLanguagePackage.TOP_SECTION__TOP_ID:
        return getTopID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TestLanguagePackage.TOP_SECTION__TOP_SECTION_STATE:
        setTopSectionState((String)newValue);
        return;
      case TestLanguagePackage.TOP_SECTION__TOP_ID:
        setTopID((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.TOP_SECTION__TOP_SECTION_STATE:
        setTopSectionState(TOP_SECTION_STATE_EDEFAULT);
        return;
      case TestLanguagePackage.TOP_SECTION__TOP_ID:
        setTopID(TOP_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TestLanguagePackage.TOP_SECTION__TOP_SECTION_STATE:
        return TOP_SECTION_STATE_EDEFAULT == null ? topSectionState != null : !TOP_SECTION_STATE_EDEFAULT.equals(topSectionState);
      case TestLanguagePackage.TOP_SECTION__TOP_ID:
        return topID != TOP_ID_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (topSectionState: ");
    result.append(topSectionState);
    result.append(", topID: ");
    result.append(topID);
    result.append(')');
    return result.toString();
  }

} //TopSectionImpl
