/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName <em>Case Name</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getSteps <em>Steps</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getExpect <em>Expect</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription()
 * @model
 * @generated
 */
public interface CaseDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Case Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Name</em>' containment reference.
   * @see #setCaseName(CaseName)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_CaseName()
   * @model containment="true"
   * @generated
   */
  CaseName getCaseName();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName <em>Case Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case Name</em>' containment reference.
   * @see #getCaseName()
   * @generated
   */
  void setCaseName(CaseName value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Steps</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference.
   * @see #setSteps(Steps)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_Steps()
   * @model containment="true"
   * @generated
   */
  Steps getSteps();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getSteps <em>Steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' containment reference.
   * @see #getSteps()
   * @generated
   */
  void setSteps(Steps value);

  /**
   * Returns the value of the '<em><b>Expect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expect</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expect</em>' containment reference.
   * @see #setExpect(Expectations)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_Expect()
   * @model containment="true"
   * @generated
   */
  Expectations getExpect();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getExpect <em>Expect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expect</em>' containment reference.
   * @see #getExpect()
   * @generated
   */
  void setExpect(Expectations value);

} // CaseDescription
