/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName <em>Case Name</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComment <em>Comment</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComponents <em>Components</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getExpect <em>Expect</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription()
 * @model
 * @generated
 */
public interface CaseDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Case Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Name</em>' containment reference.
   * @see #setCaseName(CaseName)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_CaseName()
   * @model containment="true"
   * @generated
   */
  CaseName getCaseName();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName <em>Case Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case Name</em>' containment reference.
   * @see #getCaseName()
   * @generated
   */
  void setCaseName(CaseName value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' containment reference.
   * @see #setComment(Comment)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_Comment()
   * @model containment="true"
   * @generated
   */
  Comment getComment();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComment <em>Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' containment reference.
   * @see #getComment()
   * @generated
   */
  void setComment(Comment value);

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.modes3.test.testLanguage.Component}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_Components()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponents();

  /**
   * Returns the value of the '<em><b>Expect</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.modes3.test.testLanguage.Expectations}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expect</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expect</em>' containment reference list.
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getCaseDescription_Expect()
   * @model containment="true"
   * @generated
   */
  EList<Expectations> getExpect();

} // CaseDescription
