/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Component#getTurnout <em>Turnout</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Component#getSection <em>Section</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Turnout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Turnout</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Turnout</em>' containment reference.
   * @see #setTurnout(Turnout)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getComponent_Turnout()
   * @model containment="true"
   * @generated
   */
  Turnout getTurnout();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Component#getTurnout <em>Turnout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Turnout</em>' containment reference.
   * @see #getTurnout()
   * @generated
   */
  void setTurnout(Turnout value);

  /**
   * Returns the value of the '<em><b>Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Section</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Section</em>' containment reference.
   * @see #setSection(Section)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getComponent_Section()
   * @model containment="true"
   * @generated
   */
  Section getSection();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Component#getSection <em>Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Section</em>' containment reference.
   * @see #getSection()
   * @generated
   */
  void setSection(Section value);

} // Component
