/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Divergent Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivergentSectionState <em>Divergent Section State</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivID <em>Div ID</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getDivergentSection()
 * @model
 * @generated
 */
public interface DivergentSection extends EObject
{
  /**
   * Returns the value of the '<em><b>Divergent Section State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Divergent Section State</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Divergent Section State</em>' attribute.
   * @see #setDivergentSectionState(String)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getDivergentSection_DivergentSectionState()
   * @model
   * @generated
   */
  String getDivergentSectionState();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivergentSectionState <em>Divergent Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Divergent Section State</em>' attribute.
   * @see #getDivergentSectionState()
   * @generated
   */
  void setDivergentSectionState(String value);

  /**
   * Returns the value of the '<em><b>Div ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Div ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Div ID</em>' attribute.
   * @see #setDivID(int)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getDivergentSection_DivID()
   * @model
   * @generated
   */
  int getDivID();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivID <em>Div ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Div ID</em>' attribute.
   * @see #getDivID()
   * @generated
   */
  void setDivID(int value);

} // DivergentSection
