/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expectations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getExpectedTurnoutID <em>Expected Turnout ID</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getStraightExpectation <em>Straight Expectation</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getDivergentExpectation <em>Divergent Expectation</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getTopExpectation <em>Top Expectation</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getExpectations()
 * @model
 * @generated
 */
public interface Expectations extends EObject
{
  /**
   * Returns the value of the '<em><b>Expected Turnout ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expected Turnout ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expected Turnout ID</em>' attribute.
   * @see #setExpectedTurnoutID(int)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getExpectations_ExpectedTurnoutID()
   * @model
   * @generated
   */
  int getExpectedTurnoutID();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getExpectedTurnoutID <em>Expected Turnout ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expected Turnout ID</em>' attribute.
   * @see #getExpectedTurnoutID()
   * @generated
   */
  void setExpectedTurnoutID(int value);

  /**
   * Returns the value of the '<em><b>Straight Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Straight Expectation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Straight Expectation</em>' containment reference.
   * @see #setStraightExpectation(StraightExpectation)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getExpectations_StraightExpectation()
   * @model containment="true"
   * @generated
   */
  StraightExpectation getStraightExpectation();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getStraightExpectation <em>Straight Expectation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Straight Expectation</em>' containment reference.
   * @see #getStraightExpectation()
   * @generated
   */
  void setStraightExpectation(StraightExpectation value);

  /**
   * Returns the value of the '<em><b>Divergent Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Divergent Expectation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Divergent Expectation</em>' containment reference.
   * @see #setDivergentExpectation(DivergentExpectation)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getExpectations_DivergentExpectation()
   * @model containment="true"
   * @generated
   */
  DivergentExpectation getDivergentExpectation();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getDivergentExpectation <em>Divergent Expectation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Divergent Expectation</em>' containment reference.
   * @see #getDivergentExpectation()
   * @generated
   */
  void setDivergentExpectation(DivergentExpectation value);

  /**
   * Returns the value of the '<em><b>Top Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top Expectation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top Expectation</em>' containment reference.
   * @see #setTopExpectation(TopExpectation)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getExpectations_TopExpectation()
   * @model containment="true"
   * @generated
   */
  TopExpectation getTopExpectation();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getTopExpectation <em>Top Expectation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top Expectation</em>' containment reference.
   * @see #getTopExpectation()
   * @generated
   */
  void setTopExpectation(TopExpectation value);

} // Expectations
