/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.InitialState#getTurnoutID <em>Turnout ID</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.InitialState#getTurnout <em>Turnout</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getInitialState()
 * @model
 * @generated
 */
public interface InitialState extends EObject
{
  /**
   * Returns the value of the '<em><b>Turnout ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Turnout ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Turnout ID</em>' attribute.
   * @see #setTurnoutID(int)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getInitialState_TurnoutID()
   * @model
   * @generated
   */
  int getTurnoutID();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.InitialState#getTurnoutID <em>Turnout ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Turnout ID</em>' attribute.
   * @see #getTurnoutID()
   * @generated
   */
  void setTurnoutID(int value);

  /**
   * Returns the value of the '<em><b>Turnout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Turnout</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Turnout</em>' containment reference.
   * @see #setTurnout(Turnout)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getInitialState_Turnout()
   * @model containment="true"
   * @generated
   */
  Turnout getTurnout();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.InitialState#getTurnout <em>Turnout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Turnout</em>' containment reference.
   * @see #getTurnout()
   * @generated
   */
  void setTurnout(Turnout value);

} // InitialState
