/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Straight Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.StraightSection#getStraightSectionState <em>Straight Section State</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getStraightSection()
 * @model
 * @generated
 */
public interface StraightSection extends EObject
{
  /**
   * Returns the value of the '<em><b>Straight Section State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Straight Section State</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Straight Section State</em>' attribute.
   * @see #setStraightSectionState(String)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getStraightSection_StraightSectionState()
   * @model
   * @generated
   */
  String getStraightSectionState();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.StraightSection#getStraightSectionState <em>Straight Section State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Straight Section State</em>' attribute.
   * @see #getStraightSectionState()
   * @generated
   */
  void setStraightSectionState(String value);

} // StraightSection
