/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage
 * @generated
 */
public interface TestLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestLanguageFactory eINSTANCE = hu.bme.mit.modes3.test.testLanguage.impl.TestLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Initial State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial State</em>'.
   * @generated
   */
  InitialState createInitialState();

  /**
   * Returns a new object of class '<em>Case Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Case Description</em>'.
   * @generated
   */
  CaseDescription createCaseDescription();

  /**
   * Returns a new object of class '<em>Case Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Case Name</em>'.
   * @generated
   */
  CaseName createCaseName();

  /**
   * Returns a new object of class '<em>Steps</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Steps</em>'.
   * @generated
   */
  Steps createSteps();

  /**
   * Returns a new object of class '<em>Comment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comment</em>'.
   * @generated
   */
  Comment createComment();

  /**
   * Returns a new object of class '<em>Turnout</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Turnout</em>'.
   * @generated
   */
  Turnout createTurnout();

  /**
   * Returns a new object of class '<em>Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Section</em>'.
   * @generated
   */
  Section createSection();

  /**
   * Returns a new object of class '<em>Straight Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Straight Section</em>'.
   * @generated
   */
  StraightSection createStraightSection();

  /**
   * Returns a new object of class '<em>Divergent Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Divergent Section</em>'.
   * @generated
   */
  DivergentSection createDivergentSection();

  /**
   * Returns a new object of class '<em>Top Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Section</em>'.
   * @generated
   */
  TopSection createTopSection();

  /**
   * Returns a new object of class '<em>Expectations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expectations</em>'.
   * @generated
   */
  Expectations createExpectations();

  /**
   * Returns a new object of class '<em>Straight Expectation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Straight Expectation</em>'.
   * @generated
   */
  StraightExpectation createStraightExpectation();

  /**
   * Returns a new object of class '<em>Divergent Expectation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Divergent Expectation</em>'.
   * @generated
   */
  DivergentExpectation createDivergentExpectation();

  /**
   * Returns a new object of class '<em>Top Expectation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Expectation</em>'.
   * @generated
   */
  TopExpectation createTopExpectation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TestLanguagePackage getTestLanguagePackage();

} //TestLanguageFactory
