/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface TestLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "testLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.bme.hu/mit/modes3/test/TestLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "testLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestLanguagePackage eINSTANCE = hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.ModelImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Case Description</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CASE_DESCRIPTION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CaseDescriptionImpl <em>Case Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.CaseDescriptionImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getCaseDescription()
   * @generated
   */
  int CASE_DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Case Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_DESCRIPTION__CASE_NAME = 0;

  /**
   * The feature id for the '<em><b>Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_DESCRIPTION__COMMENT = 1;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_DESCRIPTION__COMPONENTS = 2;

  /**
   * The feature id for the '<em><b>Expect</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_DESCRIPTION__EXPECT = 3;

  /**
   * The number of structural features of the '<em>Case Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_DESCRIPTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CaseNameImpl <em>Case Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.CaseNameImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getCaseName()
   * @generated
   */
  int CASE_NAME = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Case Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CommentImpl <em>Comment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.CommentImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getComment()
   * @generated
   */
  int COMMENT = 3;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT__COMMENT = 0;

  /**
   * The number of structural features of the '<em>Comment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.ComponentImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 4;

  /**
   * The feature id for the '<em><b>Turnout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__TURNOUT = 0;

  /**
   * The feature id for the '<em><b>Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__SECTION = 1;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TurnoutImpl <em>Turnout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TurnoutImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTurnout()
   * @generated
   */
  int TURNOUT = 5;

  /**
   * The feature id for the '<em><b>Turnout ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURNOUT__TURNOUT_ID = 0;

  /**
   * The feature id for the '<em><b>Turnout State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURNOUT__TURNOUT_STATE = 1;

  /**
   * The number of structural features of the '<em>Turnout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURNOUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.SectionImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getSection()
   * @generated
   */
  int SECTION = 6;

  /**
   * The feature id for the '<em><b>Straight Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__STRAIGHT_SECTION = 0;

  /**
   * The feature id for the '<em><b>Divergent Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__DIVERGENT_SECTION = 1;

  /**
   * The feature id for the '<em><b>Top Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__TOP_SECTION = 2;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.StraightSectionImpl <em>Straight Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.StraightSectionImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getStraightSection()
   * @generated
   */
  int STRAIGHT_SECTION = 7;

  /**
   * The feature id for the '<em><b>Straight Section State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_SECTION__STRAIGHT_SECTION_STATE = 0;

  /**
   * The feature id for the '<em><b>Str ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_SECTION__STR_ID = 1;

  /**
   * The number of structural features of the '<em>Straight Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_SECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentSectionImpl <em>Divergent Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.DivergentSectionImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getDivergentSection()
   * @generated
   */
  int DIVERGENT_SECTION = 8;

  /**
   * The feature id for the '<em><b>Divergent Section State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_SECTION__DIVERGENT_SECTION_STATE = 0;

  /**
   * The feature id for the '<em><b>Div ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_SECTION__DIV_ID = 1;

  /**
   * The number of structural features of the '<em>Divergent Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_SECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl <em>Top Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTopSection()
   * @generated
   */
  int TOP_SECTION = 9;

  /**
   * The feature id for the '<em><b>Top Section State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_SECTION__TOP_SECTION_STATE = 0;

  /**
   * The feature id for the '<em><b>Top ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_SECTION__TOP_ID = 1;

  /**
   * The number of structural features of the '<em>Top Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_SECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ExpectationsImpl <em>Expectations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.ExpectationsImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getExpectations()
   * @generated
   */
  int EXPECTATIONS = 10;

  /**
   * The feature id for the '<em><b>Expected Turnout ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTATIONS__EXPECTED_TURNOUT_ID = 0;

  /**
   * The feature id for the '<em><b>Straight Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTATIONS__STRAIGHT_EXPECTATION = 1;

  /**
   * The feature id for the '<em><b>Divergent Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTATIONS__DIVERGENT_EXPECTATION = 2;

  /**
   * The feature id for the '<em><b>Top Expectation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTATIONS__TOP_EXPECTATION = 3;

  /**
   * The number of structural features of the '<em>Expectations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPECTATIONS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.StraightExpectationImpl <em>Straight Expectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.StraightExpectationImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getStraightExpectation()
   * @generated
   */
  int STRAIGHT_EXPECTATION = 11;

  /**
   * The feature id for the '<em><b>Straight Expected State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE = 0;

  /**
   * The feature id for the '<em><b>Str ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_EXPECTATION__STR_ID = 1;

  /**
   * The number of structural features of the '<em>Straight Expectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAIGHT_EXPECTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl <em>Divergent Expectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getDivergentExpectation()
   * @generated
   */
  int DIVERGENT_EXPECTATION = 12;

  /**
   * The feature id for the '<em><b>Divergent Expected State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE = 0;

  /**
   * The feature id for the '<em><b>Div ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_EXPECTATION__DIV_ID = 1;

  /**
   * The number of structural features of the '<em>Divergent Expectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVERGENT_EXPECTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TopExpectationImpl <em>Top Expectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TopExpectationImpl
   * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTopExpectation()
   * @generated
   */
  int TOP_EXPECTATION = 13;

  /**
   * The feature id for the '<em><b>Top Expected State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_EXPECTATION__TOP_EXPECTED_STATE = 0;

  /**
   * The feature id for the '<em><b>Top ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_EXPECTATION__TOP_ID = 1;

  /**
   * The number of structural features of the '<em>Top Expectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_EXPECTATION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.modes3.test.testLanguage.Model#getCaseDescription <em>Case Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Case Description</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Model#getCaseDescription()
   * @see #getModel()
   * @generated
   */
  EReference getModel_CaseDescription();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription <em>Case Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case Description</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseDescription
   * @generated
   */
  EClass getCaseDescription();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName <em>Case Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Case Name</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseDescription#getCaseName()
   * @see #getCaseDescription()
   * @generated
   */
  EReference getCaseDescription_CaseName();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comment</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComment()
   * @see #getCaseDescription()
   * @generated
   */
  EReference getCaseDescription_Comment();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseDescription#getComponents()
   * @see #getCaseDescription()
   * @generated
   */
  EReference getCaseDescription_Components();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.modes3.test.testLanguage.CaseDescription#getExpect <em>Expect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expect</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseDescription#getExpect()
   * @see #getCaseDescription()
   * @generated
   */
  EReference getCaseDescription_Expect();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.CaseName <em>Case Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case Name</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseName
   * @generated
   */
  EClass getCaseName();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.CaseName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.CaseName#getName()
   * @see #getCaseName()
   * @generated
   */
  EAttribute getCaseName_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Comment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comment</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Comment
   * @generated
   */
  EClass getComment();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.Comment#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Comment#getComment()
   * @see #getComment()
   * @generated
   */
  EAttribute getComment_Comment();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Component#getTurnout <em>Turnout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Turnout</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Component#getTurnout()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Turnout();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Component#getSection <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Component#getSection()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Section();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Turnout <em>Turnout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turnout</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Turnout
   * @generated
   */
  EClass getTurnout();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.Turnout#getTurnoutID <em>Turnout ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Turnout ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Turnout#getTurnoutID()
   * @see #getTurnout()
   * @generated
   */
  EAttribute getTurnout_TurnoutID();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.Turnout#getTurnoutState <em>Turnout State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Turnout State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Turnout#getTurnoutState()
   * @see #getTurnout()
   * @generated
   */
  EAttribute getTurnout_TurnoutState();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Section#getStraightSection <em>Straight Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Straight Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Section#getStraightSection()
   * @see #getSection()
   * @generated
   */
  EReference getSection_StraightSection();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Section#getDivergentSection <em>Divergent Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Divergent Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Section#getDivergentSection()
   * @see #getSection()
   * @generated
   */
  EReference getSection_DivergentSection();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Section#getTopSection <em>Top Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Top Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Section#getTopSection()
   * @see #getSection()
   * @generated
   */
  EReference getSection_TopSection();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.StraightSection <em>Straight Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Straight Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightSection
   * @generated
   */
  EClass getStraightSection();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.StraightSection#getStraightSectionState <em>Straight Section State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Straight Section State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightSection#getStraightSectionState()
   * @see #getStraightSection()
   * @generated
   */
  EAttribute getStraightSection_StraightSectionState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.StraightSection#getStrID <em>Str ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightSection#getStrID()
   * @see #getStraightSection()
   * @generated
   */
  EAttribute getStraightSection_StrID();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection <em>Divergent Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divergent Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentSection
   * @generated
   */
  EClass getDivergentSection();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivergentSectionState <em>Divergent Section State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Divergent Section State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivergentSectionState()
   * @see #getDivergentSection()
   * @generated
   */
  EAttribute getDivergentSection_DivergentSectionState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivID <em>Div ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Div ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentSection#getDivID()
   * @see #getDivergentSection()
   * @generated
   */
  EAttribute getDivergentSection_DivID();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.TopSection <em>Top Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Section</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopSection
   * @generated
   */
  EClass getTopSection();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.TopSection#getTopSectionState <em>Top Section State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top Section State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopSection#getTopSectionState()
   * @see #getTopSection()
   * @generated
   */
  EAttribute getTopSection_TopSectionState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.TopSection#getTopID <em>Top ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopSection#getTopID()
   * @see #getTopSection()
   * @generated
   */
  EAttribute getTopSection_TopID();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.Expectations <em>Expectations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expectations</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Expectations
   * @generated
   */
  EClass getExpectations();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getExpectedTurnoutID <em>Expected Turnout ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expected Turnout ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Expectations#getExpectedTurnoutID()
   * @see #getExpectations()
   * @generated
   */
  EAttribute getExpectations_ExpectedTurnoutID();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getStraightExpectation <em>Straight Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Straight Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Expectations#getStraightExpectation()
   * @see #getExpectations()
   * @generated
   */
  EReference getExpectations_StraightExpectation();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getDivergentExpectation <em>Divergent Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Divergent Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Expectations#getDivergentExpectation()
   * @see #getExpectations()
   * @generated
   */
  EReference getExpectations_DivergentExpectation();

  /**
   * Returns the meta object for the containment reference '{@link hu.bme.mit.modes3.test.testLanguage.Expectations#getTopExpectation <em>Top Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Top Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.Expectations#getTopExpectation()
   * @see #getExpectations()
   * @generated
   */
  EReference getExpectations_TopExpectation();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.StraightExpectation <em>Straight Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Straight Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightExpectation
   * @generated
   */
  EClass getStraightExpectation();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.StraightExpectation#getStraightExpectedState <em>Straight Expected State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Straight Expected State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightExpectation#getStraightExpectedState()
   * @see #getStraightExpectation()
   * @generated
   */
  EAttribute getStraightExpectation_StraightExpectedState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.StraightExpectation#getStrID <em>Str ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.StraightExpectation#getStrID()
   * @see #getStraightExpectation()
   * @generated
   */
  EAttribute getStraightExpectation_StrID();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.DivergentExpectation <em>Divergent Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divergent Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentExpectation
   * @generated
   */
  EClass getDivergentExpectation();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.DivergentExpectation#getDivergentExpectedState <em>Divergent Expected State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Divergent Expected State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentExpectation#getDivergentExpectedState()
   * @see #getDivergentExpectation()
   * @generated
   */
  EAttribute getDivergentExpectation_DivergentExpectedState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.DivergentExpectation#getDivID <em>Div ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Div ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.DivergentExpectation#getDivID()
   * @see #getDivergentExpectation()
   * @generated
   */
  EAttribute getDivergentExpectation_DivID();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation <em>Top Expectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Expectation</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopExpectation
   * @generated
   */
  EClass getTopExpectation();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopExpectedState <em>Top Expected State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top Expected State</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopExpectedState()
   * @see #getTopExpectation()
   * @generated
   */
  EAttribute getTopExpectation_TopExpectedState();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopID <em>Top ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top ID</em>'.
   * @see hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopID()
   * @see #getTopExpectation()
   * @generated
   */
  EAttribute getTopExpectation_TopID();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TestLanguageFactory getTestLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.ModelImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Case Description</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CASE_DESCRIPTION = eINSTANCE.getModel_CaseDescription();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CaseDescriptionImpl <em>Case Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.CaseDescriptionImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getCaseDescription()
     * @generated
     */
    EClass CASE_DESCRIPTION = eINSTANCE.getCaseDescription();

    /**
     * The meta object literal for the '<em><b>Case Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_DESCRIPTION__CASE_NAME = eINSTANCE.getCaseDescription_CaseName();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_DESCRIPTION__COMMENT = eINSTANCE.getCaseDescription_Comment();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_DESCRIPTION__COMPONENTS = eINSTANCE.getCaseDescription_Components();

    /**
     * The meta object literal for the '<em><b>Expect</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_DESCRIPTION__EXPECT = eINSTANCE.getCaseDescription_Expect();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CaseNameImpl <em>Case Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.CaseNameImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getCaseName()
     * @generated
     */
    EClass CASE_NAME = eINSTANCE.getCaseName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CASE_NAME__NAME = eINSTANCE.getCaseName_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.CommentImpl <em>Comment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.CommentImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getComment()
     * @generated
     */
    EClass COMMENT = eINSTANCE.getComment();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMENT__COMMENT = eINSTANCE.getComment_Comment();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.ComponentImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Turnout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__TURNOUT = eINSTANCE.getComponent_Turnout();

    /**
     * The meta object literal for the '<em><b>Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__SECTION = eINSTANCE.getComponent_Section();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TurnoutImpl <em>Turnout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TurnoutImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTurnout()
     * @generated
     */
    EClass TURNOUT = eINSTANCE.getTurnout();

    /**
     * The meta object literal for the '<em><b>Turnout ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURNOUT__TURNOUT_ID = eINSTANCE.getTurnout_TurnoutID();

    /**
     * The meta object literal for the '<em><b>Turnout State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURNOUT__TURNOUT_STATE = eINSTANCE.getTurnout_TurnoutState();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.SectionImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Straight Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__STRAIGHT_SECTION = eINSTANCE.getSection_StraightSection();

    /**
     * The meta object literal for the '<em><b>Divergent Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__DIVERGENT_SECTION = eINSTANCE.getSection_DivergentSection();

    /**
     * The meta object literal for the '<em><b>Top Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__TOP_SECTION = eINSTANCE.getSection_TopSection();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.StraightSectionImpl <em>Straight Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.StraightSectionImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getStraightSection()
     * @generated
     */
    EClass STRAIGHT_SECTION = eINSTANCE.getStraightSection();

    /**
     * The meta object literal for the '<em><b>Straight Section State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRAIGHT_SECTION__STRAIGHT_SECTION_STATE = eINSTANCE.getStraightSection_StraightSectionState();

    /**
     * The meta object literal for the '<em><b>Str ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRAIGHT_SECTION__STR_ID = eINSTANCE.getStraightSection_StrID();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentSectionImpl <em>Divergent Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.DivergentSectionImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getDivergentSection()
     * @generated
     */
    EClass DIVERGENT_SECTION = eINSTANCE.getDivergentSection();

    /**
     * The meta object literal for the '<em><b>Divergent Section State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVERGENT_SECTION__DIVERGENT_SECTION_STATE = eINSTANCE.getDivergentSection_DivergentSectionState();

    /**
     * The meta object literal for the '<em><b>Div ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVERGENT_SECTION__DIV_ID = eINSTANCE.getDivergentSection_DivID();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl <em>Top Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TopSectionImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTopSection()
     * @generated
     */
    EClass TOP_SECTION = eINSTANCE.getTopSection();

    /**
     * The meta object literal for the '<em><b>Top Section State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_SECTION__TOP_SECTION_STATE = eINSTANCE.getTopSection_TopSectionState();

    /**
     * The meta object literal for the '<em><b>Top ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_SECTION__TOP_ID = eINSTANCE.getTopSection_TopID();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.ExpectationsImpl <em>Expectations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.ExpectationsImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getExpectations()
     * @generated
     */
    EClass EXPECTATIONS = eINSTANCE.getExpectations();

    /**
     * The meta object literal for the '<em><b>Expected Turnout ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPECTATIONS__EXPECTED_TURNOUT_ID = eINSTANCE.getExpectations_ExpectedTurnoutID();

    /**
     * The meta object literal for the '<em><b>Straight Expectation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPECTATIONS__STRAIGHT_EXPECTATION = eINSTANCE.getExpectations_StraightExpectation();

    /**
     * The meta object literal for the '<em><b>Divergent Expectation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPECTATIONS__DIVERGENT_EXPECTATION = eINSTANCE.getExpectations_DivergentExpectation();

    /**
     * The meta object literal for the '<em><b>Top Expectation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPECTATIONS__TOP_EXPECTATION = eINSTANCE.getExpectations_TopExpectation();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.StraightExpectationImpl <em>Straight Expectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.StraightExpectationImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getStraightExpectation()
     * @generated
     */
    EClass STRAIGHT_EXPECTATION = eINSTANCE.getStraightExpectation();

    /**
     * The meta object literal for the '<em><b>Straight Expected State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRAIGHT_EXPECTATION__STRAIGHT_EXPECTED_STATE = eINSTANCE.getStraightExpectation_StraightExpectedState();

    /**
     * The meta object literal for the '<em><b>Str ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRAIGHT_EXPECTATION__STR_ID = eINSTANCE.getStraightExpectation_StrID();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl <em>Divergent Expectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.DivergentExpectationImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getDivergentExpectation()
     * @generated
     */
    EClass DIVERGENT_EXPECTATION = eINSTANCE.getDivergentExpectation();

    /**
     * The meta object literal for the '<em><b>Divergent Expected State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVERGENT_EXPECTATION__DIVERGENT_EXPECTED_STATE = eINSTANCE.getDivergentExpectation_DivergentExpectedState();

    /**
     * The meta object literal for the '<em><b>Div ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIVERGENT_EXPECTATION__DIV_ID = eINSTANCE.getDivergentExpectation_DivID();

    /**
     * The meta object literal for the '{@link hu.bme.mit.modes3.test.testLanguage.impl.TopExpectationImpl <em>Top Expectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TopExpectationImpl
     * @see hu.bme.mit.modes3.test.testLanguage.impl.TestLanguagePackageImpl#getTopExpectation()
     * @generated
     */
    EClass TOP_EXPECTATION = eINSTANCE.getTopExpectation();

    /**
     * The meta object literal for the '<em><b>Top Expected State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_EXPECTATION__TOP_EXPECTED_STATE = eINSTANCE.getTopExpectation_TopExpectedState();

    /**
     * The meta object literal for the '<em><b>Top ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_EXPECTATION__TOP_ID = eINSTANCE.getTopExpectation_TopID();

  }

} //TestLanguagePackage
