/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.testLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top Expectation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopExpectedState <em>Top Expected State</em>}</li>
 *   <li>{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopID <em>Top ID</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getTopExpectation()
 * @model
 * @generated
 */
public interface TopExpectation extends EObject
{
  /**
   * Returns the value of the '<em><b>Top Expected State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top Expected State</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top Expected State</em>' attribute.
   * @see #setTopExpectedState(String)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getTopExpectation_TopExpectedState()
   * @model
   * @generated
   */
  String getTopExpectedState();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopExpectedState <em>Top Expected State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top Expected State</em>' attribute.
   * @see #getTopExpectedState()
   * @generated
   */
  void setTopExpectedState(String value);

  /**
   * Returns the value of the '<em><b>Top ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top ID</em>' attribute.
   * @see #setTopID(int)
   * @see hu.bme.mit.modes3.test.testLanguage.TestLanguagePackage#getTopExpectation_TopID()
   * @model
   * @generated
   */
  int getTopID();

  /**
   * Sets the value of the '{@link hu.bme.mit.modes3.test.testLanguage.TopExpectation#getTopID <em>Top ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top ID</em>' attribute.
   * @see #getTopID()
   * @generated
   */
  void setTopID(int value);

} // TopExpectation
