/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TestLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Model");
		private final Assignment cCaseDescriptionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCaseDescriptionCaseDescriptionParserRuleCall_0 = (RuleCall)cCaseDescriptionAssignment.eContents().get(0);
		
		//Model:
		//	caseDescription+=CaseDescription* // At least one pair of steps and expectations. 
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//caseDescription+=CaseDescription*
		public Assignment getCaseDescriptionAssignment() { return cCaseDescriptionAssignment; }
		
		//CaseDescription
		public RuleCall getCaseDescriptionCaseDescriptionParserRuleCall_0() { return cCaseDescriptionCaseDescriptionParserRuleCall_0; }
	}
	public class CaseDescriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.CaseDescription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTestCaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCaseNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCaseNameCaseNameParserRuleCall_1_0 = (RuleCall)cCaseNameAssignment_1.eContents().get(0);
		private final Assignment cCommentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCommentCommentParserRuleCall_2_0 = (RuleCall)cCommentAssignment_2.eContents().get(0);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Assignment cExpectAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpectExpectationsParserRuleCall_4_0 = (RuleCall)cExpectAssignment_4.eContents().get(0);
		
		//// A pair of steps and expectations.
		//CaseDescription:
		//	'[TestCase]'
		//	caseName=CaseName comment=Comment?
		//	components+=Component+
		//	expect+=Expectations+;
		@Override public ParserRule getRule() { return rule; }
		
		//'[TestCase]' caseName=CaseName comment=Comment? components+=Component+ expect+=Expectations+
		public Group getGroup() { return cGroup; }
		
		//'[TestCase]'
		public Keyword getTestCaseKeyword_0() { return cTestCaseKeyword_0; }
		
		//caseName=CaseName
		public Assignment getCaseNameAssignment_1() { return cCaseNameAssignment_1; }
		
		//CaseName
		public RuleCall getCaseNameCaseNameParserRuleCall_1_0() { return cCaseNameCaseNameParserRuleCall_1_0; }
		
		//comment=Comment?
		public Assignment getCommentAssignment_2() { return cCommentAssignment_2; }
		
		//Comment
		public RuleCall getCommentCommentParserRuleCall_2_0() { return cCommentCommentParserRuleCall_2_0; }
		
		//components+=Component+
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//expect+=Expectations+
		public Assignment getExpectAssignment_4() { return cExpectAssignment_4; }
		
		//Expectations
		public RuleCall getExpectExpectationsParserRuleCall_4_0() { return cExpectExpectationsParserRuleCall_4_0; }
	}
	public class CaseNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.CaseName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameOfTheTestCaseIsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//CaseName:
		//	'Name of the test case is ' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'Name of the test case is ' name=ID
		public Group getGroup() { return cGroup; }
		
		//'Name of the test case is '
		public Keyword getNameOfTheTestCaseIsKeyword_0() { return cNameOfTheTestCaseIsKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class CommentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Comment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cShortDescriptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCommentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCommentSTRINGTerminalRuleCall_2_0 = (RuleCall)cCommentAssignment_2.eContents().get(0);
		
		//Comment:
		//	'Short description' ':' comment=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Short description' ':' comment=STRING
		public Group getGroup() { return cGroup; }
		
		//'Short description'
		public Keyword getShortDescriptionKeyword_0() { return cShortDescriptionKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//comment=STRING
		public Assignment getCommentAssignment_2() { return cCommentAssignment_2; }
		
		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_2_0() { return cCommentSTRINGTerminalRuleCall_2_0; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTurnoutAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTurnoutTurnoutParserRuleCall_1_0 = (RuleCall)cTurnoutAssignment_1.eContents().get(0);
		private final Assignment cSectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSectionSectionParserRuleCall_2_0 = (RuleCall)cSectionAssignment_2.eContents().get(0);
		
		//Component:
		//	'[Component]'
		//	turnout=Turnout section=Section;
		@Override public ParserRule getRule() { return rule; }
		
		//'[Component]' turnout=Turnout section=Section
		public Group getGroup() { return cGroup; }
		
		//'[Component]'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//turnout=Turnout
		public Assignment getTurnoutAssignment_1() { return cTurnoutAssignment_1; }
		
		//Turnout
		public RuleCall getTurnoutTurnoutParserRuleCall_1_0() { return cTurnoutTurnoutParserRuleCall_1_0; }
		
		//section=Section
		public Assignment getSectionAssignment_2() { return cSectionAssignment_2; }
		
		//Section
		public RuleCall getSectionSectionParserRuleCall_2_0() { return cSectionSectionParserRuleCall_2_0; }
	}
	public class TurnoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Turnout");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTurnoutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTurnoutIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTurnoutIDINTTerminalRuleCall_1_0 = (RuleCall)cTurnoutIDAssignment_1.eContents().get(0);
		private final Keyword cIsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTurnoutStateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cTurnoutStateAlternatives_3_0 = (Alternatives)cTurnoutStateAssignment_3.eContents().get(0);
		private final Keyword cTurnoutStateSTRAIGHTKeyword_3_0_0 = (Keyword)cTurnoutStateAlternatives_3_0.eContents().get(0);
		private final Keyword cTurnoutStateDIVERGENTKeyword_3_0_1 = (Keyword)cTurnoutStateAlternatives_3_0.eContents().get(1);
		
		//// A turnout has a state.
		//Turnout:
		//	'Turnout ' turnoutID=INT ' is ' turnoutState=('STRAIGHT' | 'DIVERGENT');
		@Override public ParserRule getRule() { return rule; }
		
		//'Turnout ' turnoutID=INT ' is ' turnoutState=('STRAIGHT' | 'DIVERGENT')
		public Group getGroup() { return cGroup; }
		
		//'Turnout '
		public Keyword getTurnoutKeyword_0() { return cTurnoutKeyword_0; }
		
		//turnoutID=INT
		public Assignment getTurnoutIDAssignment_1() { return cTurnoutIDAssignment_1; }
		
		//INT
		public RuleCall getTurnoutIDINTTerminalRuleCall_1_0() { return cTurnoutIDINTTerminalRuleCall_1_0; }
		
		//' is '
		public Keyword getIsKeyword_2() { return cIsKeyword_2; }
		
		//turnoutState=('STRAIGHT' | 'DIVERGENT')
		public Assignment getTurnoutStateAssignment_3() { return cTurnoutStateAssignment_3; }
		
		//('STRAIGHT' | 'DIVERGENT')
		public Alternatives getTurnoutStateAlternatives_3_0() { return cTurnoutStateAlternatives_3_0; }
		
		//'STRAIGHT'
		public Keyword getTurnoutStateSTRAIGHTKeyword_3_0_0() { return cTurnoutStateSTRAIGHTKeyword_3_0_0; }
		
		//'DIVERGENT'
		public Keyword getTurnoutStateDIVERGENTKeyword_3_0_1() { return cTurnoutStateDIVERGENTKeyword_3_0_1; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStraightSectionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStraightSectionStraightSectionParserRuleCall_0_0 = (RuleCall)cStraightSectionAssignment_0.eContents().get(0);
		private final Assignment cDivergentSectionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDivergentSectionDivergentSectionParserRuleCall_1_0 = (RuleCall)cDivergentSectionAssignment_1.eContents().get(0);
		private final Assignment cTopSectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTopSectionTopSectionParserRuleCall_2_0 = (RuleCall)cTopSectionAssignment_2.eContents().get(0);
		
		//// A section has a position where it connects to the turnout, and a state.
		//Section:
		//	straightSection=StraightSection divergentSection=DivergentSection topSection=TopSection;
		@Override public ParserRule getRule() { return rule; }
		
		//straightSection=StraightSection divergentSection=DivergentSection topSection=TopSection
		public Group getGroup() { return cGroup; }
		
		//straightSection=StraightSection
		public Assignment getStraightSectionAssignment_0() { return cStraightSectionAssignment_0; }
		
		//StraightSection
		public RuleCall getStraightSectionStraightSectionParserRuleCall_0_0() { return cStraightSectionStraightSectionParserRuleCall_0_0; }
		
		//divergentSection=DivergentSection
		public Assignment getDivergentSectionAssignment_1() { return cDivergentSectionAssignment_1; }
		
		//DivergentSection
		public RuleCall getDivergentSectionDivergentSectionParserRuleCall_1_0() { return cDivergentSectionDivergentSectionParserRuleCall_1_0; }
		
		//topSection=TopSection
		public Assignment getTopSectionAssignment_2() { return cTopSectionAssignment_2; }
		
		//TopSection
		public RuleCall getTopSectionTopSectionParserRuleCall_2_0() { return cTopSectionTopSectionParserRuleCall_2_0; }
	}
	public class StraightSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.StraightSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromSTRAIGHTIsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStraightSectionStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cStraightSectionStateAlternatives_1_0 = (Alternatives)cStraightSectionStateAssignment_1.eContents().get(0);
		private final Keyword cStraightSectionStateFREEKeyword_1_0_0 = (Keyword)cStraightSectionStateAlternatives_1_0.eContents().get(0);
		private final Keyword cStraightSectionStateOCCUPIEDKeyword_1_0_1 = (Keyword)cStraightSectionStateAlternatives_1_0.eContents().get(1);
		private final Keyword cStraightIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStrIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStrIDINTTerminalRuleCall_4_0 = (RuleCall)cStrIDAssignment_4.eContents().get(0);
		
		//StraightSection:
		//	'Section connecting from STRAIGHT is ' straightSectionState=('FREE' | 'OCCUPIED')
		//	'Straight id' ':' strID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from STRAIGHT is ' straightSectionState=('FREE' | 'OCCUPIED') 'Straight id' ':' strID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from STRAIGHT is '
		public Keyword getSectionConnectingFromSTRAIGHTIsKeyword_0() { return cSectionConnectingFromSTRAIGHTIsKeyword_0; }
		
		//straightSectionState=('FREE' | 'OCCUPIED')
		public Assignment getStraightSectionStateAssignment_1() { return cStraightSectionStateAssignment_1; }
		
		//('FREE' | 'OCCUPIED')
		public Alternatives getStraightSectionStateAlternatives_1_0() { return cStraightSectionStateAlternatives_1_0; }
		
		//'FREE'
		public Keyword getStraightSectionStateFREEKeyword_1_0_0() { return cStraightSectionStateFREEKeyword_1_0_0; }
		
		//'OCCUPIED'
		public Keyword getStraightSectionStateOCCUPIEDKeyword_1_0_1() { return cStraightSectionStateOCCUPIEDKeyword_1_0_1; }
		
		//'Straight id'
		public Keyword getStraightIdKeyword_2() { return cStraightIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//strID=INT
		public Assignment getStrIDAssignment_4() { return cStrIDAssignment_4; }
		
		//INT
		public RuleCall getStrIDINTTerminalRuleCall_4_0() { return cStrIDINTTerminalRuleCall_4_0; }
	}
	public class DivergentSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.DivergentSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromDIVERGENTIsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDivergentSectionStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cDivergentSectionStateAlternatives_1_0 = (Alternatives)cDivergentSectionStateAssignment_1.eContents().get(0);
		private final Keyword cDivergentSectionStateFREEKeyword_1_0_0 = (Keyword)cDivergentSectionStateAlternatives_1_0.eContents().get(0);
		private final Keyword cDivergentSectionStateOCCUPIEDKeyword_1_0_1 = (Keyword)cDivergentSectionStateAlternatives_1_0.eContents().get(1);
		private final Keyword cDivergentIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDivIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDivIDINTTerminalRuleCall_4_0 = (RuleCall)cDivIDAssignment_4.eContents().get(0);
		
		//DivergentSection:
		//	'Section connecting from DIVERGENT is ' divergentSectionState=('FREE' | 'OCCUPIED')
		//	'Divergent id' ':' divID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from DIVERGENT is ' divergentSectionState=('FREE' | 'OCCUPIED') 'Divergent id' ':' divID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from DIVERGENT is '
		public Keyword getSectionConnectingFromDIVERGENTIsKeyword_0() { return cSectionConnectingFromDIVERGENTIsKeyword_0; }
		
		//divergentSectionState=('FREE' | 'OCCUPIED')
		public Assignment getDivergentSectionStateAssignment_1() { return cDivergentSectionStateAssignment_1; }
		
		//('FREE' | 'OCCUPIED')
		public Alternatives getDivergentSectionStateAlternatives_1_0() { return cDivergentSectionStateAlternatives_1_0; }
		
		//'FREE'
		public Keyword getDivergentSectionStateFREEKeyword_1_0_0() { return cDivergentSectionStateFREEKeyword_1_0_0; }
		
		//'OCCUPIED'
		public Keyword getDivergentSectionStateOCCUPIEDKeyword_1_0_1() { return cDivergentSectionStateOCCUPIEDKeyword_1_0_1; }
		
		//'Divergent id'
		public Keyword getDivergentIdKeyword_2() { return cDivergentIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//divID=INT
		public Assignment getDivIDAssignment_4() { return cDivIDAssignment_4; }
		
		//INT
		public RuleCall getDivIDINTTerminalRuleCall_4_0() { return cDivIDINTTerminalRuleCall_4_0; }
	}
	public class TopSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.TopSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromTOPIsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTopSectionStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTopSectionStateAlternatives_1_0 = (Alternatives)cTopSectionStateAssignment_1.eContents().get(0);
		private final Keyword cTopSectionStateFREEKeyword_1_0_0 = (Keyword)cTopSectionStateAlternatives_1_0.eContents().get(0);
		private final Keyword cTopSectionStateOCCUPIEDKeyword_1_0_1 = (Keyword)cTopSectionStateAlternatives_1_0.eContents().get(1);
		private final Keyword cTopIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTopIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTopIDINTTerminalRuleCall_4_0 = (RuleCall)cTopIDAssignment_4.eContents().get(0);
		
		//TopSection:
		//	'Section connecting from TOP is ' topSectionState=('FREE' | 'OCCUPIED')
		//	'Top id' ':' topID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from TOP is ' topSectionState=('FREE' | 'OCCUPIED') 'Top id' ':' topID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from TOP is '
		public Keyword getSectionConnectingFromTOPIsKeyword_0() { return cSectionConnectingFromTOPIsKeyword_0; }
		
		//topSectionState=('FREE' | 'OCCUPIED')
		public Assignment getTopSectionStateAssignment_1() { return cTopSectionStateAssignment_1; }
		
		//('FREE' | 'OCCUPIED')
		public Alternatives getTopSectionStateAlternatives_1_0() { return cTopSectionStateAlternatives_1_0; }
		
		//'FREE'
		public Keyword getTopSectionStateFREEKeyword_1_0_0() { return cTopSectionStateFREEKeyword_1_0_0; }
		
		//'OCCUPIED'
		public Keyword getTopSectionStateOCCUPIEDKeyword_1_0_1() { return cTopSectionStateOCCUPIEDKeyword_1_0_1; }
		
		//'Top id'
		public Keyword getTopIdKeyword_2() { return cTopIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//topID=INT
		public Assignment getTopIDAssignment_4() { return cTopIDAssignment_4; }
		
		//INT
		public RuleCall getTopIDINTTerminalRuleCall_4_0() { return cTopIDINTTerminalRuleCall_4_0; }
	}
	public class ExpectationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.Expectations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpectedComponentsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTurnoutKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpectedTurnoutIDAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpectedTurnoutIDINTTerminalRuleCall_2_0 = (RuleCall)cExpectedTurnoutIDAssignment_2.eContents().get(0);
		private final Assignment cStraightExpectationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStraightExpectationStraightExpectationParserRuleCall_3_0 = (RuleCall)cStraightExpectationAssignment_3.eContents().get(0);
		private final Assignment cDivergentExpectationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDivergentExpectationDivergentExpectationParserRuleCall_4_0 = (RuleCall)cDivergentExpectationAssignment_4.eContents().get(0);
		private final Assignment cTopExpectationAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTopExpectationTopExpectationParserRuleCall_5_0 = (RuleCall)cTopExpectationAssignment_5.eContents().get(0);
		
		//// Shows which sections are expected state of each section
		//Expectations:
		//	'[ExpectedComponents]'
		//	'Turnout ' expectedTurnoutID=INT
		//	straightExpectation=StraightExpectation divergentExpectation=DivergentExpectation topExpectation=TopExpectation;
		@Override public ParserRule getRule() { return rule; }
		
		//'[ExpectedComponents]' 'Turnout ' expectedTurnoutID=INT straightExpectation=StraightExpectation
		//divergentExpectation=DivergentExpectation topExpectation=TopExpectation
		public Group getGroup() { return cGroup; }
		
		//'[ExpectedComponents]'
		public Keyword getExpectedComponentsKeyword_0() { return cExpectedComponentsKeyword_0; }
		
		//'Turnout '
		public Keyword getTurnoutKeyword_1() { return cTurnoutKeyword_1; }
		
		//expectedTurnoutID=INT
		public Assignment getExpectedTurnoutIDAssignment_2() { return cExpectedTurnoutIDAssignment_2; }
		
		//INT
		public RuleCall getExpectedTurnoutIDINTTerminalRuleCall_2_0() { return cExpectedTurnoutIDINTTerminalRuleCall_2_0; }
		
		//straightExpectation=StraightExpectation
		public Assignment getStraightExpectationAssignment_3() { return cStraightExpectationAssignment_3; }
		
		//StraightExpectation
		public RuleCall getStraightExpectationStraightExpectationParserRuleCall_3_0() { return cStraightExpectationStraightExpectationParserRuleCall_3_0; }
		
		//divergentExpectation=DivergentExpectation
		public Assignment getDivergentExpectationAssignment_4() { return cDivergentExpectationAssignment_4; }
		
		//DivergentExpectation
		public RuleCall getDivergentExpectationDivergentExpectationParserRuleCall_4_0() { return cDivergentExpectationDivergentExpectationParserRuleCall_4_0; }
		
		//topExpectation=TopExpectation
		public Assignment getTopExpectationAssignment_5() { return cTopExpectationAssignment_5; }
		
		//TopExpectation
		public RuleCall getTopExpectationTopExpectationParserRuleCall_5_0() { return cTopExpectationTopExpectationParserRuleCall_5_0; }
	}
	public class StraightExpectationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.StraightExpectation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromSTRAIGHTIsExpectedToBeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStraightExpectedStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cStraightExpectedStateAlternatives_1_0 = (Alternatives)cStraightExpectedStateAssignment_1.eContents().get(0);
		private final Keyword cStraightExpectedStateENABLEDKeyword_1_0_0 = (Keyword)cStraightExpectedStateAlternatives_1_0.eContents().get(0);
		private final Keyword cStraightExpectedStateDISABLEDKeyword_1_0_1 = (Keyword)cStraightExpectedStateAlternatives_1_0.eContents().get(1);
		private final Keyword cStraightIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStrIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStrIDINTTerminalRuleCall_4_0 = (RuleCall)cStrIDAssignment_4.eContents().get(0);
		
		//StraightExpectation:
		//	'Section connecting from STRAIGHT is expected to be ' straightExpectedState=('ENABLED' | 'DISABLED')
		//	'Straight id' ':' strID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from STRAIGHT is expected to be ' straightExpectedState=('ENABLED' | 'DISABLED') 'Straight id' ':'
		//strID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from STRAIGHT is expected to be '
		public Keyword getSectionConnectingFromSTRAIGHTIsExpectedToBeKeyword_0() { return cSectionConnectingFromSTRAIGHTIsExpectedToBeKeyword_0; }
		
		//straightExpectedState=('ENABLED' | 'DISABLED')
		public Assignment getStraightExpectedStateAssignment_1() { return cStraightExpectedStateAssignment_1; }
		
		//('ENABLED' | 'DISABLED')
		public Alternatives getStraightExpectedStateAlternatives_1_0() { return cStraightExpectedStateAlternatives_1_0; }
		
		//'ENABLED'
		public Keyword getStraightExpectedStateENABLEDKeyword_1_0_0() { return cStraightExpectedStateENABLEDKeyword_1_0_0; }
		
		//'DISABLED'
		public Keyword getStraightExpectedStateDISABLEDKeyword_1_0_1() { return cStraightExpectedStateDISABLEDKeyword_1_0_1; }
		
		//'Straight id'
		public Keyword getStraightIdKeyword_2() { return cStraightIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//strID=INT
		public Assignment getStrIDAssignment_4() { return cStrIDAssignment_4; }
		
		//INT
		public RuleCall getStrIDINTTerminalRuleCall_4_0() { return cStrIDINTTerminalRuleCall_4_0; }
	}
	public class DivergentExpectationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.DivergentExpectation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromDIVERGENTIsExpectedToBeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDivergentExpectedStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cDivergentExpectedStateAlternatives_1_0 = (Alternatives)cDivergentExpectedStateAssignment_1.eContents().get(0);
		private final Keyword cDivergentExpectedStateENABLEDKeyword_1_0_0 = (Keyword)cDivergentExpectedStateAlternatives_1_0.eContents().get(0);
		private final Keyword cDivergentExpectedStateDISABLEDKeyword_1_0_1 = (Keyword)cDivergentExpectedStateAlternatives_1_0.eContents().get(1);
		private final Keyword cDivergentIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDivIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDivIDINTTerminalRuleCall_4_0 = (RuleCall)cDivIDAssignment_4.eContents().get(0);
		
		//DivergentExpectation:
		//	'Section connecting from DIVERGENT is expected to be ' divergentExpectedState=('ENABLED' | 'DISABLED')
		//	'Divergent id' ':' divID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from DIVERGENT is expected to be ' divergentExpectedState=('ENABLED' | 'DISABLED') 'Divergent id'
		//':' divID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from DIVERGENT is expected to be '
		public Keyword getSectionConnectingFromDIVERGENTIsExpectedToBeKeyword_0() { return cSectionConnectingFromDIVERGENTIsExpectedToBeKeyword_0; }
		
		//divergentExpectedState=('ENABLED' | 'DISABLED')
		public Assignment getDivergentExpectedStateAssignment_1() { return cDivergentExpectedStateAssignment_1; }
		
		//('ENABLED' | 'DISABLED')
		public Alternatives getDivergentExpectedStateAlternatives_1_0() { return cDivergentExpectedStateAlternatives_1_0; }
		
		//'ENABLED'
		public Keyword getDivergentExpectedStateENABLEDKeyword_1_0_0() { return cDivergentExpectedStateENABLEDKeyword_1_0_0; }
		
		//'DISABLED'
		public Keyword getDivergentExpectedStateDISABLEDKeyword_1_0_1() { return cDivergentExpectedStateDISABLEDKeyword_1_0_1; }
		
		//'Divergent id'
		public Keyword getDivergentIdKeyword_2() { return cDivergentIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//divID=INT
		public Assignment getDivIDAssignment_4() { return cDivIDAssignment_4; }
		
		//INT
		public RuleCall getDivIDINTTerminalRuleCall_4_0() { return cDivIDINTTerminalRuleCall_4_0; }
	}
	public class TopExpectationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "hu.bme.mit.modes3.test.TestLanguage.TopExpectation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionConnectingFromTOPIsExpectedToBeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTopExpectedStateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTopExpectedStateAlternatives_1_0 = (Alternatives)cTopExpectedStateAssignment_1.eContents().get(0);
		private final Keyword cTopExpectedStateENABLEDKeyword_1_0_0 = (Keyword)cTopExpectedStateAlternatives_1_0.eContents().get(0);
		private final Keyword cTopExpectedStateDISABLEDKeyword_1_0_1 = (Keyword)cTopExpectedStateAlternatives_1_0.eContents().get(1);
		private final Keyword cTopIdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTopIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTopIDINTTerminalRuleCall_4_0 = (RuleCall)cTopIDAssignment_4.eContents().get(0);
		
		//TopExpectation:
		//	'Section connecting from TOP is expected to be ' topExpectedState=('ENABLED' | 'DISABLED')
		//	'Top id' ':' topID=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section connecting from TOP is expected to be ' topExpectedState=('ENABLED' | 'DISABLED') 'Top id' ':' topID=INT
		public Group getGroup() { return cGroup; }
		
		//'Section connecting from TOP is expected to be '
		public Keyword getSectionConnectingFromTOPIsExpectedToBeKeyword_0() { return cSectionConnectingFromTOPIsExpectedToBeKeyword_0; }
		
		//topExpectedState=('ENABLED' | 'DISABLED')
		public Assignment getTopExpectedStateAssignment_1() { return cTopExpectedStateAssignment_1; }
		
		//('ENABLED' | 'DISABLED')
		public Alternatives getTopExpectedStateAlternatives_1_0() { return cTopExpectedStateAlternatives_1_0; }
		
		//'ENABLED'
		public Keyword getTopExpectedStateENABLEDKeyword_1_0_0() { return cTopExpectedStateENABLEDKeyword_1_0_0; }
		
		//'DISABLED'
		public Keyword getTopExpectedStateDISABLEDKeyword_1_0_1() { return cTopExpectedStateDISABLEDKeyword_1_0_1; }
		
		//'Top id'
		public Keyword getTopIdKeyword_2() { return cTopIdKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//topID=INT
		public Assignment getTopIDAssignment_4() { return cTopIDAssignment_4; }
		
		//INT
		public RuleCall getTopIDINTTerminalRuleCall_4_0() { return cTopIDINTTerminalRuleCall_4_0; }
	}
	
	
	private final ModelElements pModel;
	private final CaseDescriptionElements pCaseDescription;
	private final CaseNameElements pCaseName;
	private final CommentElements pComment;
	private final ComponentElements pComponent;
	private final TurnoutElements pTurnout;
	private final SectionElements pSection;
	private final StraightSectionElements pStraightSection;
	private final DivergentSectionElements pDivergentSection;
	private final TopSectionElements pTopSection;
	private final ExpectationsElements pExpectations;
	private final StraightExpectationElements pStraightExpectation;
	private final DivergentExpectationElements pDivergentExpectation;
	private final TopExpectationElements pTopExpectation;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TestLanguageGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pCaseDescription = new CaseDescriptionElements();
		this.pCaseName = new CaseNameElements();
		this.pComment = new CommentElements();
		this.pComponent = new ComponentElements();
		this.pTurnout = new TurnoutElements();
		this.pSection = new SectionElements();
		this.pStraightSection = new StraightSectionElements();
		this.pDivergentSection = new DivergentSectionElements();
		this.pTopSection = new TopSectionElements();
		this.pExpectations = new ExpectationsElements();
		this.pStraightExpectation = new StraightExpectationElements();
		this.pDivergentExpectation = new DivergentExpectationElements();
		this.pTopExpectation = new TopExpectationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("hu.bme.mit.modes3.test.TestLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	caseDescription+=CaseDescription* // At least one pair of steps and expectations. 
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//// A pair of steps and expectations.
	//CaseDescription:
	//	'[TestCase]'
	//	caseName=CaseName comment=Comment?
	//	components+=Component+
	//	expect+=Expectations+;
	public CaseDescriptionElements getCaseDescriptionAccess() {
		return pCaseDescription;
	}
	
	public ParserRule getCaseDescriptionRule() {
		return getCaseDescriptionAccess().getRule();
	}
	
	//CaseName:
	//	'Name of the test case is ' name=ID;
	public CaseNameElements getCaseNameAccess() {
		return pCaseName;
	}
	
	public ParserRule getCaseNameRule() {
		return getCaseNameAccess().getRule();
	}
	
	//Comment:
	//	'Short description' ':' comment=STRING;
	public CommentElements getCommentAccess() {
		return pComment;
	}
	
	public ParserRule getCommentRule() {
		return getCommentAccess().getRule();
	}
	
	//Component:
	//	'[Component]'
	//	turnout=Turnout section=Section;
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//// A turnout has a state.
	//Turnout:
	//	'Turnout ' turnoutID=INT ' is ' turnoutState=('STRAIGHT' | 'DIVERGENT');
	public TurnoutElements getTurnoutAccess() {
		return pTurnout;
	}
	
	public ParserRule getTurnoutRule() {
		return getTurnoutAccess().getRule();
	}
	
	//// A section has a position where it connects to the turnout, and a state.
	//Section:
	//	straightSection=StraightSection divergentSection=DivergentSection topSection=TopSection;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//StraightSection:
	//	'Section connecting from STRAIGHT is ' straightSectionState=('FREE' | 'OCCUPIED')
	//	'Straight id' ':' strID=INT;
	public StraightSectionElements getStraightSectionAccess() {
		return pStraightSection;
	}
	
	public ParserRule getStraightSectionRule() {
		return getStraightSectionAccess().getRule();
	}
	
	//DivergentSection:
	//	'Section connecting from DIVERGENT is ' divergentSectionState=('FREE' | 'OCCUPIED')
	//	'Divergent id' ':' divID=INT;
	public DivergentSectionElements getDivergentSectionAccess() {
		return pDivergentSection;
	}
	
	public ParserRule getDivergentSectionRule() {
		return getDivergentSectionAccess().getRule();
	}
	
	//TopSection:
	//	'Section connecting from TOP is ' topSectionState=('FREE' | 'OCCUPIED')
	//	'Top id' ':' topID=INT;
	public TopSectionElements getTopSectionAccess() {
		return pTopSection;
	}
	
	public ParserRule getTopSectionRule() {
		return getTopSectionAccess().getRule();
	}
	
	//// Shows which sections are expected state of each section
	//Expectations:
	//	'[ExpectedComponents]'
	//	'Turnout ' expectedTurnoutID=INT
	//	straightExpectation=StraightExpectation divergentExpectation=DivergentExpectation topExpectation=TopExpectation;
	public ExpectationsElements getExpectationsAccess() {
		return pExpectations;
	}
	
	public ParserRule getExpectationsRule() {
		return getExpectationsAccess().getRule();
	}
	
	//StraightExpectation:
	//	'Section connecting from STRAIGHT is expected to be ' straightExpectedState=('ENABLED' | 'DISABLED')
	//	'Straight id' ':' strID=INT;
	public StraightExpectationElements getStraightExpectationAccess() {
		return pStraightExpectation;
	}
	
	public ParserRule getStraightExpectationRule() {
		return getStraightExpectationAccess().getRule();
	}
	
	//DivergentExpectation:
	//	'Section connecting from DIVERGENT is expected to be ' divergentExpectedState=('ENABLED' | 'DISABLED')
	//	'Divergent id' ':' divID=INT;
	public DivergentExpectationElements getDivergentExpectationAccess() {
		return pDivergentExpectation;
	}
	
	public ParserRule getDivergentExpectationRule() {
		return getDivergentExpectationAccess().getRule();
	}
	
	//TopExpectation:
	//	'Section connecting from TOP is expected to be ' topExpectedState=('ENABLED' | 'DISABLED')
	//	'Top id' ':' topID=INT;
	public TopExpectationElements getTopExpectationAccess() {
		return pTopExpectation;
	}
	
	public ParserRule getTopExpectationRule() {
		return getTopExpectationAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
