/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TestLanguageScopeProvider extends AbstractTestLanguageScopeProvider {

}
