/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test;

import hu.bme.mit.modes3.test.AbstractTestLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TestLanguageRuntimeModule extends AbstractTestLanguageRuntimeModule {
}
