/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTestLanguageScopeProvider extends DelegatingScopeProvider {
}
