/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.modes3.test.validation;

import hu.bme.mit.modes3.test.validation.AbstractTestLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TestLanguageValidator extends AbstractTestLanguageValidator {
}
